# -------- Build stage --------
FROM gradle:8.10.2-jdk17 AS build
WORKDIR /workspace
COPY build.gradle.kts settings.gradle.kts gradlew* ./
COPY gradle ./gradle
RUN ./gradlew dependencies --no-daemon || true
COPY . .
RUN ./gradlew clean bootJar -x test --no-daemon

# -------- Runtime stage --------
FROM eclipse-temurin:17-jdk-jammy
WORKDIR /app
COPY --from=build /workspace/build/libs/*.jar .
RUN chmod +r *.jar
ENTRYPOINT ["java","-jar","/app/phoneNumberVerify-0.0.1-SNAPSHOT.jar"]
